export type TagObj<Tag extends string = HTMLTags, Attribute extends string = HTMLAttributes> = {
    attribute?: Partial<Record<Attribute, string>>
    element: Array<Partial<Record<Tag, TagObj>>> | string
}

export type HTMLTags =
    | "a"
    | "abbr"
    | "acronym"
    | "address"
    | "applet"
    | "area"
    | "article"
    | "aside"
    | "audio"
    | "b"
    | "base"
    | "basefont"
    | "bdi"
    | "bdo"
    | "big"
    | "blockquote"
    | "body"
    | "br"
    | "button"
    | "canvas"
    | "caption"
    | "center"
    | "cite"
    | "code"
    | "col"
    | "colgroup"
    | "data"
    | "datalist"
    | "dd"
    | "del"
    | "details"
    | "dfn"
    | "dialog"
    | "dir"
    | "div"
    | "dl"
    | "dt"
    | "em"
    | "embed"
    | "fieldset"
    | "figcaption"
    | "figure"
    | "font"
    | "footer"
    | "form"
    | "frame"
    | "frameset"
    | "h1"
    | "h2"
    | "h3"
    | "h4"
    | "h5"
    | "h6"
    | "head"
    | "header"
    | "hgroup"
    | "hr"
    | "html"
    | "i"
    | "iframe"
    | "img"
    | "input"
    | "ins"
    | "kbd"
    | "label"
    | "legend"
    | "li"
    | "link"
    | "main"
    | "map"
    | "mark"
    | "menu"
    | "meta"
    | "meter"
    | "nav"
    | "noframes"
    | "noscript"
    | "object"
    | "ol"
    | "optgroup"
    | "option"
    | "output"
    | "p"
    | "param"
    | "picture"
    | "pre"
    | "progress"
    | "q"
    | "rp"
    | "rt"
    | "ruby"
    | "s"
    | "samp"
    | "script"
    | "search"
    | "section"
    | "select"
    | "small"
    | "source"
    | "span"
    | "strike"
    | "strong"
    | "style"
    | "sub"
    | "summary"
    | "sup"
    | "svg"
    | "table"
    | "tbody"
    | "td"
    | "template"
    | "textarea"
    | "tfoot"
    | "th"
    | "thead"
    | "time"
    | "title"
    | "tr"
    | "track"
    | "tt"
    | "u"
    | "ul"
    | "var"
    | "video"
    | "wbr"

export type HTMLAttributes =
    | `accept`
    | `accept-charset`
    | `accesskey`
    | `action`
    | `alt`
    | `async`
    | `autocomplete`
    | `autofocus`
    | `autoplay`
    | `charset`
    | `checked`
    | `cite`
    | `class`
    | `cols`
    | `colspan`
    | `content`
    | `contenteditable`
    | `controls`
    | `coords`
    | `data`
    | `datetime`
    | `default`
    | `defer`
    | `dir`
    | `dirname`
    | `disabled`
    | `download`
    | `draggable`
    | `enctype`
    | `enterkeyhint`
    | `for`
    | `form`
    | `formaction`
    | `headers`
    | `height`
    | `hidden`
    | `high`
    | `href`
    | `hreflang`
    | `http-equiv`
    | `id`
    | `inert`
    | `inputmode`
    | `ismap`
    | `kind`
    | `label `
    | `lang`
    | `list`
    | `loop`
    | `low`
    | `max`
    | `maxlength`
    | `media`
    | `method`
    | `min`
    | `multiple`
    | `muted`
    | `name`
    | `novalidate`
    | `onabort`
    | `onafterprint`
    | `onbeforeprint `
    | `onbeforeunload`
    | `onblur`
    | `oncanplay`
    | `oncanplaythrough`
    | `onchange`
    | `onclick`
    | `oncontextmenu`
    | `oncopy`
    | `oncuechange`
    | `oncut`
    | `ondblclick `
    | `ondrag`
    | `ondragend`
    | `ondragenter`
    | `ondragleave`
    | `ondragover`
    | `ondragstart`
    | `ondrop`
    | `ondurationchange`
    | `onemptied`
    | `onended`
    | `onerror`
    | `onfocus`
    | `onhashchange`
    | `oninput`
    | `oninvalid`
    | `onkeydown`
    | `onkeypress`
    | `onkeyup`
    | `onload`
    | `onloadeddata`
    | `onloadedmetadata`
    | `onloadstart `
    | `onmousedown`
    | `onmousemove`
    | `onmouseout`
    | `onmouseover`
    | `onmouseup`
    | `onmousewheel`
    | `onoffline`
    | `ononline`
    | `onpageshow`
    | `onpaste`
    | `onpause `
    | `onplay`
    | `onplaying`
    | `onprogress`
    | `onratechange`
    | `onreset`
    | `onresize`
    | `onscroll`
    | `onsearch`
    | `onseeked`
    | `onseeking`
    | `onselect`
    | `onstalled `
    | `onsubmit`
    | `onsuspend`
    | `ontimeupdate`
    | `ontoggle`
    | `onunload`
    | `onvolumechange`
    | `onwaiting`
    | `onwheel`
    | `open`
    | `optimum`
    | `pattern`
    | `placeholder `
    | `popover`
    | `popovertarget`
    | `popovertargetaction`
    | `poster`
    | `preload`
    | `readonly`
    | `rel`
    | `required`
    | `reversed`
    | `rows`
    | `rowspan`
    | `sandbox`
    | `scope`
    | `selected`
    | `shape`
    | `size`
    | `sizes`
    | `span`
    | `spellcheck`
    | `src`
    | `srcdoc`
    | `srclang`
    | `srcset`
    | `start`
    | `step`
    | `style`
    | `tabindex`
    | `target`
    | `title`
    | `translate `
    | `usemap`
    | `value`
    | `width`
    | `wrap`
